# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_firstForm(object):
    def setupUi(self, firstForm):
        firstForm.setObjectName("firstForm")
        firstForm.resize(400, 300)
        self.gridLayout_2 = QtWidgets.QGridLayout(firstForm)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widgetfirst = QtWidgets.QWidget(firstForm)
        self.widgetfirst.setObjectName("widgetfirst")
        self.gridLayout = QtWidgets.QGridLayout(self.widgetfirst)
        self.gridLayout.setObjectName("gridLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.widgetfirst)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.calendarWidget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widgetfirst, 0, 0, 1, 1)

        self.retranslateUi(firstForm)
        QtCore.QMetaObject.connectSlotsByName(firstForm)

    def retranslateUi(self, firstForm):
        _translate = QtCore.QCoreApplication.translate
        firstForm.setWindowTitle(_translate("firstForm", "Form"))

