# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_secondForm(object):
    def setupUi(self, secondForm):
        secondForm.setObjectName("secondForm")
        secondForm.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(secondForm)
        self.gridLayout.setObjectName("gridLayout")
        self.widgetsecond = QtWidgets.QWidget(secondForm)
        self.widgetsecond.setObjectName("widgetsecond")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetsecond)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.widgetsecond)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.gridLayout.addWidget(self.widgetsecond, 0, 0, 1, 1)

        self.retranslateUi(secondForm)
        QtCore.QMetaObject.connectSlotsByName(secondForm)

    def retranslateUi(self, secondForm):
        _translate = QtCore.QCoreApplication.translate
        secondForm.setWindowTitle(_translate("secondForm", "Form"))
